# Generated by Django 3.2.4 on 2021-06-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_name', models.CharField(max_length=20)),
                ('User_id', models.IntegerField(primary_key=True, serialize=False)),
                ('User_email', models.TextField()),
            ],
        ),
    ]
